name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - graphviz
  - pydotplus
  - seaborn
  - scipy
  - mlxtend
  - pandas_profiling
